/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package project481;

import java.util.ArrayList;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
    public static boolean search(ArrayList<Integer> array, int idx1, int idx2, int guess) {
        System.out.println("inside search");
        int sum=0;
        if (array == null) return false;
  
        for (int i = idx1; i<=idx2; i++) {
           sum+=array.get(i);
        }
        if(sum==guess) return true;
        return false;
      }
}
